export const TRAMOS = [
  'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J',
  'K', 'L', 'M', 'N1', 'N2', 'O', 'P', 'Q', 'R', 'S', 'T',
  'U', 'V', 'W', 'X', 'Y1', 'Y2', 'Z',
  'AZ', 'BZ', 'CZ', 'DZ',
];

export const CAIDAS = Array.from({ length: 29 }, (_, i) => i + 1);

export const ATRAVIESOS = ['1', '2'];

export const PROTOCOLOS = [
  { id: 'PICE1',       codigo: 'PICE-01', nombre: 'Excavación',           subtipo: null },
  { id: 'PICE2_RADIER', codigo: 'PICE-02', nombre: 'Hormigones Radier',   subtipo: 'radier' },
  { id: 'PICE2_MURO',  codigo: 'PICE-02', nombre: 'Hormigones Muro',      subtipo: 'muro' },
  { id: 'PICE3',       codigo: 'PICE-03', nombre: 'Moldajes',              subtipo: null },
  { id: 'PICE4_RADIER', codigo: 'PICE-04', nombre: 'Enfierradura Radier', subtipo: 'radier' },
  { id: 'PICE4_MURO',  codigo: 'PICE-04', nombre: 'Enfierradura Muro',    subtipo: 'muro' },
  { id: 'G5',          codigo: 'G5',      nombre: 'Emplantillado',         subtipo: null },
  { id: 'HA_RADIER',  codigo: 'H.A.',    nombre: 'Control H.A. Radier',   subtipo: 'radier' },
  { id: 'HA_MURO',    codigo: 'H.A.',    nombre: 'Control H.A. Muro',     subtipo: 'muro' },
];

export const CHECKLISTS = {
  PICE1: [
    { id: 'pr_verificados',        label: 'PR verificados' },
    { id: 'replanteo_conforme',    label: 'Replanteo conforme a planos' },
    { id: 'cotas_excavacion',      label: 'Cotas de excavación' },
    { id: 'espesor_capas_relleno', label: 'Espesor de capas de relleno conforme' },
    { id: 'ancho_excavacion',      label: 'Ancho excavación' },
    { id: 'registro_fotografico',  label: 'Registro fotográfico' },
    { id: 'compactacion',          label: 'Compactación' },
    { id: 'aprobacion_hormigonado', label: 'Aprobación para hormigonado' },
  ],
  PICE2_RADIER: [
    { id: 'tratamiento_junta',     label: 'Tratamientos de junta' },
    { id: 'limpieza_seccion',      label: 'Limpieza de la sección a hormigonar' },
    { id: 'herramientas_adecuadas', label: 'Herramientas adecuadas' },
    { id: 'cono_conforme',         label: 'Cono conforme' },
    { id: 'vibrado_adecuado',      label: 'Vibrado adecuado' },
    { id: 'platachado_afinado',    label: 'Platachado / Afinado' },
    { id: 'curado',                label: 'Curado' },
  ],
  PICE2_MURO: [
    { id: 'tratamiento_junta',     label: 'Tratamientos de junta' },
    { id: 'limpieza_seccion',      label: 'Limpieza de la sección a hormigonar' },
    { id: 'herramientas_adecuadas', label: 'Herramientas adecuadas' },
    { id: 'cono_conforme',         label: 'Cono conforme' },
    { id: 'vibrado_adecuado',      label: 'Vibrado adecuado' },
    { id: 'platachado_afinado',    label: 'Platachado / Afinado' },
    { id: 'curado',                label: 'Curado' },
  ],
  PICE3: [
    { id: 'desmoldante',           label: 'Desmoldante' },
    { id: 'fijacion_moldajes',     label: 'Fijación moldajes' },
    { id: 'fijacion_puntales',     label: 'Fijación puntales' },
    { id: 'herramientas_adecuadas', label: 'Herramientas adecuadas' },
    { id: 'estanquidad',           label: 'Estanquidad' },
    { id: 'limpieza',              label: 'Limpieza' },
    { id: 'junta_dilatacion',      label: 'Junta de dilatación' },
    { id: 'junta_contraccion',     label: 'Junta de contracción' },
    { id: 'water_stop',            label: 'Wáter stop' },
    { id: 'aprobacion_hormigonado', label: 'Aprobación para hormigonado' },
  ],
  PICE4_RADIER: [
    { id: 'diametros_conforme',    label: 'Diámetros conforme' },
    { id: 'separacion_conforme',   label: 'Separación conforme' },
    { id: 'recubrimiento_conforme', label: 'Recubrimiento conforme' },
    { id: 'armadura_fija',         label: 'Armadura fija' },
    { id: 'traslapes',             label: 'Traslapes' },
    { id: 'limpieza',              label: 'Limpieza' },
    { id: 'aprobacion',            label: 'Aprobación' },
  ],
  PICE4_MURO: [
    { id: 'diametros_conforme',    label: 'Diámetros conforme' },
    { id: 'separacion_conforme',   label: 'Separación conforme' },
    { id: 'recubrimiento_conforme', label: 'Recubrimiento conforme' },
    { id: 'armadura_fija',         label: 'Armadura fija' },
    { id: 'traslapes',             label: 'Traslapes' },
    { id: 'limpieza',              label: 'Limpieza' },
    { id: 'aprobacion',            label: 'Aprobación' },
  ],
  G5: [],
};

export const USUARIOS = [
  'Álvaro Muñoz',
  'Diego Oñate',
  'Otro',
];

export const KM_DATA = {
  tramo: {
    'A':  { inicio: '10,3',     fin: '237,7' },
    'B':  { inicio: '249,7',    fin: '337,7' },
    'C':  { inicio: '349,7',    fin: '457,7' },
    'D':  { inicio: '469,7',    fin: '587,7' },
    'E':  { inicio: '599,7',    fin: '777,7' },
    'F':  { inicio: '789,7',    fin: '827,7' },
    'G':  { inicio: '839,7',    fin: '1.037,7' },
    'H':  { inicio: '1.049,7',  fin: '1.107,7' },
    'I':  { inicio: '1.119,7',  fin: '1.297,7' },
    'J':  { inicio: '1.309,7',  fin: '1.407,7' },
    'K':  { inicio: '1.419,7',  fin: '1.517,7' },
    'L':  { inicio: '1.529,7',  fin: '1.607,7' },
    'M':  { inicio: '1.619,7',  fin: '1.737,7' },
    'N1': { inicio: '1.749,7',  fin: '1.763,0' },
    'N2': { inicio: '1.769,0',  fin: '1.937,7' },
    'O':  { inicio: '1.949,7',  fin: '2.057,7' },
    'P':  { inicio: '2.069,7',  fin: '2.157,7' },
    'Q':  { inicio: '2.169,7',  fin: '2.277,7' },
    'R':  { inicio: '2.289,7',  fin: '2.377,7' },
    'S':  { inicio: '2.389,7',  fin: '2.427,7' },
    'T':  { inicio: '2.439,7',  fin: '2.517,7' },
    'U':  { inicio: '2.529,7',  fin: '2.627,7' },
    'V':  { inicio: '2.639,7',  fin: '2.717,7' },
    'W':  { inicio: '2.729,7',  fin: '2.807,7' },
    'X':  { inicio: '2.819,7',  fin: '2.937,7' },
    'Y1': { inicio: '2.949,7',  fin: '3.002,7' },
    'Y2': { inicio: '3.008,7',  fin: '3.037,7' },
    'Z':  { inicio: '3.049,7',  fin: '3.267,7' },
    'AZ': { inicio: '3.279,7',  fin: '3.417,7' },
    'BZ': { inicio: '3.429,7',  fin: '3.537,7' },
    'CZ': { inicio: '3.549,7',  fin: '3.597,7' },
    'DZ': { inicio: '3.609,7',  fin: '3.934,2' },
  },
  caida: {
    '1':  { inicio: '237,7',    fin: '249,7' },
    '2':  { inicio: '337,7',    fin: '349,7' },
    '3':  { inicio: '457,7',    fin: '469,7' },
    '4':  { inicio: '587,7',    fin: '599,7' },
    '5':  { inicio: '777,7',    fin: '789,7' },
    '6':  { inicio: '827,7',    fin: '839,7' },
    '7':  { inicio: '1.037,7',  fin: '1.049,7' },
    '8':  { inicio: '1.107,7',  fin: '1.119,7' },
    '9':  { inicio: '1.297,7',  fin: '1.309,7' },
    '10': { inicio: '1.407,7',  fin: '1.419,7' },
    '11': { inicio: '1.517,7',  fin: '1.529,7' },
    '12': { inicio: '1.607,7',  fin: '1.619,7' },
    '13': { inicio: '1.737,7',  fin: '1.749,7' },
    '14': { inicio: '1.937,7',  fin: '1.949,7' },
    '15': { inicio: '2.057,7',  fin: '2.069,7' },
    '16': { inicio: '2.157,7',  fin: '2.169,7' },
    '17': { inicio: '2.277,7',  fin: '2.289,7' },
    '18': { inicio: '2.377,7',  fin: '2.389,7' },
    '19': { inicio: '2.427,7',  fin: '2.439,7' },
    '20': { inicio: '2.517,7',  fin: '2.529,7' },
    '21': { inicio: '2.627,7',  fin: '2.639,7' },
    '22': { inicio: '2.717,7',  fin: '2.729,7' },
    '23': { inicio: '2.807,7',  fin: '2.819,7' },
    '24': { inicio: '2.937,7',  fin: '2.949,7' },
    '25': { inicio: '3.037,7',  fin: '3.049,7' },
    '26': { inicio: '3.267,7',  fin: '3.279,7' },
    '27': { inicio: '3.417,7',  fin: '3.429,7' },
    '28': { inicio: '3.537,7',  fin: '3.549,7' },
    '29': { inicio: '3.597,7',  fin: '3.609,7' },
  },
  atravieso: {
    '1': { inicio: '1.763,0', fin: '1.769,0' },
    '2': { inicio: '3.002,7', fin: '3.008,7' },
  },
};
